### ISSUE TITLE
[Bug texte] SPPED

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#1]
![image](https://user-images.githubusercontent.com/26553241/104821746-48f27d00-583e-11eb-842b-8e48ec3f6714.png)

**Comment by Koxx3** [comment]
fixed

**Comment by Koxx3** [comment]
https://github.com/Koxx3/SmartController_SmartDisplay_android/commit/d1ad78a98a9bf6132da0601b8a029490a0f60aaf
