### ISSUE TITLE
[Bug] Demande d'activation de la localisation

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#2]
L'application affiche ce message de temps à autres : 

![image](https://user-images.githubusercontent.com/26553241/104821777-7b03df00-583e-11eb-957b-09a1e1447f6b.png)

Méthode pour reproduire le bug : https://youtu.be/kuCqTKVmAL0

**Comment by jojolll** [comment]
L'

**Comment by Koxx3** [comment]
seems fixed with version installed from Android studio. reopen if not.
