### ISSUE TITLE
[Bug] Calcul de la vitesse moyenne

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#3]
Au tout début, la vitesse moyenne est complètement erronnée, avec des valeurs qui commencent au dessus des 1000km/h.

![image](https://user-images.githubusercontent.com/26553241/104821831-e6e64780-583e-11eb-9ab0-552a019de0ab.png)

Se produit systématiquement

**Comment by Koxx3** [comment]
first fix test
https://github.com/Koxx3/SmartController_SmartDisplay_android/commit/8ee614f38a7e496f44741f8cf2a0e54a02fa66d3

**Comment by Koxx3** [comment]
first fix test2

**Comment by jojolll** [comment]
ça semble pire qu'avant ! Le calcul a l'air éventuellement correct quand la vitesse augmente, mais dès que la vitesse actuelle descend sous la vitesse moyenne ça déconne complètement 

https://photos.app.goo.gl/KX4iuMNHheRiuAce9

**Comment by Koxx3** [comment]
testé ajd... et ok ;)
