### ISSUE TITLE
[Probablement un bug ?] Appairage en erreur

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#4]
Lorsque l'on essaie d'appairer un SmartController a l'application, alors qu'il y a un autre périphérique bluetooth connecté (enceinte bluetooth dans mon cas) alors l'appairage échoue après avoir entré le code d'appairage, avec un code d'erreur 81 (trop de tentatives a priori) 
![image](https://user-images.githubusercontent.com/26553241/104821901-68d67080-583f-11eb-9a41-bd367759ca7a.png)
Erreur sur le téléphone après avoir entré un code correct : 
![image](https://user-images.githubusercontent.com/26553241/104821908-72f86f00-583f-11eb-97ae-91bcb7e18f59.png)

--> si on déconnecte l'autre périphérique, l'appairage s'effectue normalement
Ensuite, on peut se connecter aux 2 périphériques simultanément sans souci

**Comment by Koxx3** [comment]
closed until we can find another device failing
