### ISSUE TITLE
[Amélioration] Désactivation beacon

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#5]
La désactivation du "Bluetooth mode lock" dans les settings suite à un déclenchement du verrouillage de la trot (lock : ON Beacon) ne réinitialise pas le verrouillage, la trot reste lock.

Cas d'utilisation : beacon oubliée, besoin de rider sans

**Comment by Koxx3** [comment]
en réfléchissant, il y a pleins de cas où je trouve pas ca intéréssant.
le bouton delock existe dans l'app. il suffit de débloquer pour delocker.
si on delock automatiquement en sortie de settings alors que c'est un lock qui a été mis manuellement, c'est dommage et l'utilisateur risque de pas le voir.
