### ISSUE TITLE
[Amélioration] Electric brake time between mode shift 

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#6]
Plusieurs idées ici. Déjà il serait peut être bien d'avoir des paliers de 50ms par exemple pour un réglage plus facile. 

Ensuite,  l'ajout d'un second paramètre qui sera le délai du premier changement uniquement, au moment ou le freinage est détecté, permettrai de compenser le temps de switch plus long lorsque le freinage est détecté depuis la liaison série Minimo.

Actuellement, avec un réglage à 400ms, j'ai approximativement 6-700ms dans le mode 1 (temps de détection + de switch), puis 400ms mode 2, 400ms mode 3.

**Comment by Koxx3** [comment]
je regarde pour les "steps" du slider.
Pour les delais, oui, faut voir ;)

**Comment by Koxx3** [comment]
le slider est maintenant par tranche de 50ms.

ce mode ne sera pas amélioré car il est impresvisible. la latence sur
l'info qui revient du controleur est entre 5 et 200ms.
le mode a privilégié est celui pour le frein est connecté au
smartcontroller 😉 (0 latence)
