### ISSUE TITLE
[Amélioration grahique] Problème d'affichage "petits" ecran

### ISSUE THREAD

**Issue by jojolll** [Koxx3/SmartController_SmartDisplay_android#7]
Sur mon Android 7 de 5.2 pouces, sans modifier les DPI système, j'ai les 3 derniers item de l'écran d'accueil qui ne s'affichent pas.

Modèle : Honor 5C

Sur un équivalent 5.5 pouces (Asus Z00UD ou Zenfone 2 Selfie), souci moins prononcé, mais le compteur TIME n'apparait pas : 
![image](https://user-images.githubusercontent.com/26553241/105609317-bce5d580-5da8-11eb-8c70-54c0521b7cb7.png)

**Comment by Koxx3** [comment]
la page a été rendue 'scrollable'. a voir si ca suffit.

**Comment by jojolll** [comment]
C'est nickel, de toute façon les infos les plus critiques sont en haut 👍
